language: ruby
before_install:
  - gem install bundler
before_script:
  - "bin/setup"
script:
  - "bin/test"
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
