language: ruby
before_script:
  - "bundle exec rake compile"
script:
  - "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
notifications:
  emails:
    - tsukasa.oishi@gmail.com
